### ISSUE TITLE
META: Plan to Merge Taller changes

### ISSUE THREAD

**Issue by recidive** [TallerWebSolutions/choko#2]
Here is what it needs for accepting some changes made into taller fork/branch and making them into Choko core.
- [ ] Tag Element: need to update the branch and make a pull request
- [x] CKReplace: need pull request re-roll
- [x] Query/Params on reference fields: need pull to discuss
- [x] Empty Regions (alwaysRender): needs re-roll (commit comments)
- [x] Empty list panels/pages: re-roll
- [ ] No-html panels: need to test alternative
- [ ] Changes in route.js: need to evaluate (H)
- [ ] Email login feature: need to merge choko master and create a pull request to re-evaluate approach
- [ ] Rename app.css tp choko.css: need to evaluate (H)
- [ ] Restangular: re-roll branch to discuss better
- [x] CORS: need to add a setting on settings.json and update pull request
